version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
  api:
    env_file:
      - ./prod.env
    environment:
      - PGHOST=db
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - db
  # frontend:
  #   build: ./frontend/
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules/
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - api