version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
  api:
    environment:
      - PGHOST=db
    build: 
      context: ../../backend-api/
      dockerfile: Dockerfile.dev
    volumes: 
      - ../../backend-api/:/usr/src/app
    ports: 
      - "3000:3000"
    depends_on:
      - db
